# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42ee9384bf86769f46818f7c08e4a620e678f035f084dece2c6af99b0191b110dc34897186d433a33b5137c608dd12d5c221ce5caf91faf0fa998a0c546681fe

test:
  secret_key_base: 9f3234231bb1f8446df0c81ae5b97c7b640b439e099545dc58a06d88519d550adb4ecc6170c45f5e9c2f32c038d75e6d8bf8d85a2422be649c25df5b4c2851ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
